export const ADD_TASK = 'ADD_TASK';
export const ADD_ASYNC_TASK = 'ADD_ASYNC_TASK';
export const ADD_ASYNC_TASK_PENDING = 'ADD_ASYNC_TASK_PENDING';
export const ADD_ASYNC_TASK_FULFILLED = 'ADD_ASYNC_TASK_FULFILLED';
export const ADD_ASYNC_TASK_REJECTED = 'ADD_ASYNC_TASK_REJECTED';
export const DELETE_TASK = 'DELETE_TASK';
