#!/bin/bash
# to enable this on your local environment run:
# cp ./pre-commit .git/hooks/pre-commit
# chmod +x .git/hooks/pre-commit
# npm run lint
# npm run flow
# CI=true npm run test

if [ $? -ne 0 ]
then
  echo "Please fix the problems (unit tests and/or eslint style checking) before committing"
  exit 1
fi
