// flow-typed signature: af8bd322760463f573435291c9614891
// flow-typed version: <<STUB>>/cuid_v^1.3.8/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cuid/build/client-cuid' {
  declare module.exports: any;
}

declare module 'cuid/build/server-cuid' {
  declare module.exports: any;
}

declare module 'cuid/dist/browser-cuid' {
  declare module.exports: any;
}

declare module 'cuid/dist/node-cuid' {
  declare module.exports: any;
}

declare module 'cuid/source/client/index' {
  declare module.exports: any;
}

declare module 'cuid/source/index' {
  declare module.exports: any;
}

declare module 'cuid/source/server/index' {
  declare module.exports: any;
}

declare module 'cuid/test/client/index' {
  declare module.exports: any;
}

declare module 'cuid/test/client/launcher' {
  declare module.exports: any;
}

declare module 'cuid/test/client/sauceReporter' {
  declare module.exports: any;
}

declare module 'cuid/test/server/index' {
  declare module.exports: any;
}

declare module 'cuid/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cuid/build/client-cuid.js' {
  declare module.exports: $Exports<'cuid/build/client-cuid'>;
}
declare module 'cuid/build/server-cuid.js' {
  declare module.exports: $Exports<'cuid/build/server-cuid'>;
}
declare module 'cuid/dist/browser-cuid.js' {
  declare module.exports: $Exports<'cuid/dist/browser-cuid'>;
}
declare module 'cuid/dist/node-cuid.js' {
  declare module.exports: $Exports<'cuid/dist/node-cuid'>;
}
declare module 'cuid/source/client/index.js' {
  declare module.exports: $Exports<'cuid/source/client/index'>;
}
declare module 'cuid/source/index.js' {
  declare module.exports: $Exports<'cuid/source/index'>;
}
declare module 'cuid/source/server/index.js' {
  declare module.exports: $Exports<'cuid/source/server/index'>;
}
declare module 'cuid/test/client/index.js' {
  declare module.exports: $Exports<'cuid/test/client/index'>;
}
declare module 'cuid/test/client/launcher.js' {
  declare module.exports: $Exports<'cuid/test/client/launcher'>;
}
declare module 'cuid/test/client/sauceReporter.js' {
  declare module.exports: $Exports<'cuid/test/client/sauceReporter'>;
}
declare module 'cuid/test/server/index.js' {
  declare module.exports: $Exports<'cuid/test/server/index'>;
}
declare module 'cuid/webpack.config.js' {
  declare module.exports: $Exports<'cuid/webpack.config'>;
}
