// flow-typed signature: 309c980dd9aac7d8c5500d5fe0249bef
// flow-typed version: <<STUB>>/enzyme-redux_v^0.1.6/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme-redux/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme-redux/lib/index.js' {
  declare module.exports: $Exports<'enzyme-redux/lib/index'>;
}
