// flow-typed signature: 52c6a7de58b2945e496e046761191d8f
// flow-typed version: <<STUB>>/vexflow_v^1.2.83/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vexflow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vexflow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vexflow/Gruntfile' {
  declare module.exports: any;
}

declare module 'vexflow/releases/vexflow-debug' {
  declare module.exports: any;
}

declare module 'vexflow/releases/vexflow-legacy-debug' {
  declare module.exports: any;
}

declare module 'vexflow/releases/vexflow-legacy-min' {
  declare module.exports: any;
}

declare module 'vexflow/releases/vexflow-min' {
  declare module.exports: any;
}

declare module 'vexflow/releases/vexflow-tests' {
  declare module.exports: any;
}

declare module 'vexflow/src/accidental' {
  declare module.exports: any;
}

declare module 'vexflow/src/annotation' {
  declare module.exports: any;
}

declare module 'vexflow/src/articulation' {
  declare module.exports: any;
}

declare module 'vexflow/src/barnote' {
  declare module.exports: any;
}

declare module 'vexflow/src/beam' {
  declare module.exports: any;
}

declare module 'vexflow/src/bend' {
  declare module.exports: any;
}

declare module 'vexflow/src/boundingbox' {
  declare module.exports: any;
}

declare module 'vexflow/src/boundingboxcomputation' {
  declare module.exports: any;
}

declare module 'vexflow/src/canvascontext' {
  declare module.exports: any;
}

declare module 'vexflow/src/clef' {
  declare module.exports: any;
}

declare module 'vexflow/src/clefnote' {
  declare module.exports: any;
}

declare module 'vexflow/src/crescendo' {
  declare module.exports: any;
}

declare module 'vexflow/src/curve' {
  declare module.exports: any;
}

declare module 'vexflow/src/dot' {
  declare module.exports: any;
}

declare module 'vexflow/src/easyscore' {
  declare module.exports: any;
}

declare module 'vexflow/src/element' {
  declare module.exports: any;
}

declare module 'vexflow/src/factory' {
  declare module.exports: any;
}

declare module 'vexflow/src/fonts/gonville_all' {
  declare module.exports: any;
}

declare module 'vexflow/src/fonts/gonville_original' {
  declare module.exports: any;
}

declare module 'vexflow/src/fonts/gonville' {
  declare module.exports: any;
}

declare module 'vexflow/src/fonts/vexflow_font' {
  declare module.exports: any;
}

declare module 'vexflow/src/formatter' {
  declare module.exports: any;
}

declare module 'vexflow/src/fraction' {
  declare module.exports: any;
}

declare module 'vexflow/src/frethandfinger' {
  declare module.exports: any;
}

declare module 'vexflow/src/ghostnote' {
  declare module.exports: any;
}

declare module 'vexflow/src/glyph' {
  declare module.exports: any;
}

declare module 'vexflow/src/gracenote' {
  declare module.exports: any;
}

declare module 'vexflow/src/gracenotegroup' {
  declare module.exports: any;
}

declare module 'vexflow/src/gracetabnote' {
  declare module.exports: any;
}

declare module 'vexflow/src/header' {
  declare module.exports: any;
}

declare module 'vexflow/src/index' {
  declare module.exports: any;
}

declare module 'vexflow/src/keymanager' {
  declare module.exports: any;
}

declare module 'vexflow/src/keysignature' {
  declare module.exports: any;
}

declare module 'vexflow/src/modifier' {
  declare module.exports: any;
}

declare module 'vexflow/src/modifiercontext' {
  declare module.exports: any;
}

declare module 'vexflow/src/music' {
  declare module.exports: any;
}

declare module 'vexflow/src/note' {
  declare module.exports: any;
}

declare module 'vexflow/src/notehead' {
  declare module.exports: any;
}

declare module 'vexflow/src/notesubgroup' {
  declare module.exports: any;
}

declare module 'vexflow/src/ornament' {
  declare module.exports: any;
}

declare module 'vexflow/src/parser' {
  declare module.exports: any;
}

declare module 'vexflow/src/pedalmarking' {
  declare module.exports: any;
}

declare module 'vexflow/src/raphaelcontext' {
  declare module.exports: any;
}

declare module 'vexflow/src/registry' {
  declare module.exports: any;
}

declare module 'vexflow/src/renderer' {
  declare module.exports: any;
}

declare module 'vexflow/src/stave' {
  declare module.exports: any;
}

declare module 'vexflow/src/stavebarline' {
  declare module.exports: any;
}

declare module 'vexflow/src/staveconnector' {
  declare module.exports: any;
}

declare module 'vexflow/src/stavehairpin' {
  declare module.exports: any;
}

declare module 'vexflow/src/staveline' {
  declare module.exports: any;
}

declare module 'vexflow/src/stavemodifier' {
  declare module.exports: any;
}

declare module 'vexflow/src/stavenote' {
  declare module.exports: any;
}

declare module 'vexflow/src/staverepetition' {
  declare module.exports: any;
}

declare module 'vexflow/src/stavesection' {
  declare module.exports: any;
}

declare module 'vexflow/src/stavetempo' {
  declare module.exports: any;
}

declare module 'vexflow/src/stavetext' {
  declare module.exports: any;
}

declare module 'vexflow/src/stavetie' {
  declare module.exports: any;
}

declare module 'vexflow/src/stavevolta' {
  declare module.exports: any;
}

declare module 'vexflow/src/stem' {
  declare module.exports: any;
}

declare module 'vexflow/src/stemmablenote' {
  declare module.exports: any;
}

declare module 'vexflow/src/stringnumber' {
  declare module.exports: any;
}

declare module 'vexflow/src/strokes' {
  declare module.exports: any;
}

declare module 'vexflow/src/svgcontext' {
  declare module.exports: any;
}

declare module 'vexflow/src/system' {
  declare module.exports: any;
}

declare module 'vexflow/src/tables' {
  declare module.exports: any;
}

declare module 'vexflow/src/tabnote' {
  declare module.exports: any;
}

declare module 'vexflow/src/tabslide' {
  declare module.exports: any;
}

declare module 'vexflow/src/tabstave' {
  declare module.exports: any;
}

declare module 'vexflow/src/tabtie' {
  declare module.exports: any;
}

declare module 'vexflow/src/textbracket' {
  declare module.exports: any;
}

declare module 'vexflow/src/textdynamics' {
  declare module.exports: any;
}

declare module 'vexflow/src/textnote' {
  declare module.exports: any;
}

declare module 'vexflow/src/tickable' {
  declare module.exports: any;
}

declare module 'vexflow/src/tickcontext' {
  declare module.exports: any;
}

declare module 'vexflow/src/timesignature' {
  declare module.exports: any;
}

declare module 'vexflow/src/timesignote' {
  declare module.exports: any;
}

declare module 'vexflow/src/tremolo' {
  declare module.exports: any;
}

declare module 'vexflow/src/tuning' {
  declare module.exports: any;
}

declare module 'vexflow/src/tuplet' {
  declare module.exports: any;
}

declare module 'vexflow/src/vex' {
  declare module.exports: any;
}

declare module 'vexflow/src/vibrato' {
  declare module.exports: any;
}

declare module 'vexflow/src/vibratobracket' {
  declare module.exports: any;
}

declare module 'vexflow/src/voice' {
  declare module.exports: any;
}

declare module 'vexflow/src/voicegroup' {
  declare module.exports: any;
}

declare module 'vexflow/tests/accidental_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/annotation_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/articulation_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/auto_beam_formatting_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/bach_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/barline_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/beam_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/bend_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/boundingbox_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/clef_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/curve_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/dot_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/easyscore_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/factory_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/formatter_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/ghostnote_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/gracenote_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/gracetabnote_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/key_clef_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/keymanager_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/keysignature_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/mocks' {
  declare module.exports: any;
}

declare module 'vexflow/tests/modifier_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/music_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/notehead_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/notesubgroup_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/ornament_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/parser_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/pedalmarking_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/percussion_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/registry_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/rests_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/rhythm_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/run' {
  declare module.exports: any;
}

declare module 'vexflow/tests/stave_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/staveconnector_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/stavehairpin_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/staveline_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/stavemodifier_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/stavenote_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/stavetie_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/stringnumber_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/strokes_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/support/jquery' {
  declare module.exports: any;
}

declare module 'vexflow/tests/support/qunit' {
  declare module.exports: any;
}

declare module 'vexflow/tests/support/raphael' {
  declare module.exports: any;
}

declare module 'vexflow/tests/tabnote_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/tabslide_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/tabstave_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/tabtie_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/textbracket_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/textnote_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/threevoice_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/tickcontext_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/timesignature_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/tuning_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/tuplet_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/vexflow_test_helpers' {
  declare module.exports: any;
}

declare module 'vexflow/tests/vibrato_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/vibratobracket_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tests/voice_tests' {
  declare module.exports: any;
}

declare module 'vexflow/tools/generate_svg_images' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vexflow/Gruntfile.js' {
  declare module.exports: $Exports<'vexflow/Gruntfile'>;
}
declare module 'vexflow/releases/vexflow-debug.js' {
  declare module.exports: $Exports<'vexflow/releases/vexflow-debug'>;
}
declare module 'vexflow/releases/vexflow-legacy-debug.js' {
  declare module.exports: $Exports<'vexflow/releases/vexflow-legacy-debug'>;
}
declare module 'vexflow/releases/vexflow-legacy-min.js' {
  declare module.exports: $Exports<'vexflow/releases/vexflow-legacy-min'>;
}
declare module 'vexflow/releases/vexflow-min.js' {
  declare module.exports: $Exports<'vexflow/releases/vexflow-min'>;
}
declare module 'vexflow/releases/vexflow-tests.js' {
  declare module.exports: $Exports<'vexflow/releases/vexflow-tests'>;
}
declare module 'vexflow/src/accidental.js' {
  declare module.exports: $Exports<'vexflow/src/accidental'>;
}
declare module 'vexflow/src/annotation.js' {
  declare module.exports: $Exports<'vexflow/src/annotation'>;
}
declare module 'vexflow/src/articulation.js' {
  declare module.exports: $Exports<'vexflow/src/articulation'>;
}
declare module 'vexflow/src/barnote.js' {
  declare module.exports: $Exports<'vexflow/src/barnote'>;
}
declare module 'vexflow/src/beam.js' {
  declare module.exports: $Exports<'vexflow/src/beam'>;
}
declare module 'vexflow/src/bend.js' {
  declare module.exports: $Exports<'vexflow/src/bend'>;
}
declare module 'vexflow/src/boundingbox.js' {
  declare module.exports: $Exports<'vexflow/src/boundingbox'>;
}
declare module 'vexflow/src/boundingboxcomputation.js' {
  declare module.exports: $Exports<'vexflow/src/boundingboxcomputation'>;
}
declare module 'vexflow/src/canvascontext.js' {
  declare module.exports: $Exports<'vexflow/src/canvascontext'>;
}
declare module 'vexflow/src/clef.js' {
  declare module.exports: $Exports<'vexflow/src/clef'>;
}
declare module 'vexflow/src/clefnote.js' {
  declare module.exports: $Exports<'vexflow/src/clefnote'>;
}
declare module 'vexflow/src/crescendo.js' {
  declare module.exports: $Exports<'vexflow/src/crescendo'>;
}
declare module 'vexflow/src/curve.js' {
  declare module.exports: $Exports<'vexflow/src/curve'>;
}
declare module 'vexflow/src/dot.js' {
  declare module.exports: $Exports<'vexflow/src/dot'>;
}
declare module 'vexflow/src/easyscore.js' {
  declare module.exports: $Exports<'vexflow/src/easyscore'>;
}
declare module 'vexflow/src/element.js' {
  declare module.exports: $Exports<'vexflow/src/element'>;
}
declare module 'vexflow/src/factory.js' {
  declare module.exports: $Exports<'vexflow/src/factory'>;
}
declare module 'vexflow/src/fonts/gonville_all.js' {
  declare module.exports: $Exports<'vexflow/src/fonts/gonville_all'>;
}
declare module 'vexflow/src/fonts/gonville_original.js' {
  declare module.exports: $Exports<'vexflow/src/fonts/gonville_original'>;
}
declare module 'vexflow/src/fonts/gonville.js' {
  declare module.exports: $Exports<'vexflow/src/fonts/gonville'>;
}
declare module 'vexflow/src/fonts/vexflow_font.js' {
  declare module.exports: $Exports<'vexflow/src/fonts/vexflow_font'>;
}
declare module 'vexflow/src/formatter.js' {
  declare module.exports: $Exports<'vexflow/src/formatter'>;
}
declare module 'vexflow/src/fraction.js' {
  declare module.exports: $Exports<'vexflow/src/fraction'>;
}
declare module 'vexflow/src/frethandfinger.js' {
  declare module.exports: $Exports<'vexflow/src/frethandfinger'>;
}
declare module 'vexflow/src/ghostnote.js' {
  declare module.exports: $Exports<'vexflow/src/ghostnote'>;
}
declare module 'vexflow/src/glyph.js' {
  declare module.exports: $Exports<'vexflow/src/glyph'>;
}
declare module 'vexflow/src/gracenote.js' {
  declare module.exports: $Exports<'vexflow/src/gracenote'>;
}
declare module 'vexflow/src/gracenotegroup.js' {
  declare module.exports: $Exports<'vexflow/src/gracenotegroup'>;
}
declare module 'vexflow/src/gracetabnote.js' {
  declare module.exports: $Exports<'vexflow/src/gracetabnote'>;
}
declare module 'vexflow/src/header.js' {
  declare module.exports: $Exports<'vexflow/src/header'>;
}
declare module 'vexflow/src/index.js' {
  declare module.exports: $Exports<'vexflow/src/index'>;
}
declare module 'vexflow/src/keymanager.js' {
  declare module.exports: $Exports<'vexflow/src/keymanager'>;
}
declare module 'vexflow/src/keysignature.js' {
  declare module.exports: $Exports<'vexflow/src/keysignature'>;
}
declare module 'vexflow/src/modifier.js' {
  declare module.exports: $Exports<'vexflow/src/modifier'>;
}
declare module 'vexflow/src/modifiercontext.js' {
  declare module.exports: $Exports<'vexflow/src/modifiercontext'>;
}
declare module 'vexflow/src/music.js' {
  declare module.exports: $Exports<'vexflow/src/music'>;
}
declare module 'vexflow/src/note.js' {
  declare module.exports: $Exports<'vexflow/src/note'>;
}
declare module 'vexflow/src/notehead.js' {
  declare module.exports: $Exports<'vexflow/src/notehead'>;
}
declare module 'vexflow/src/notesubgroup.js' {
  declare module.exports: $Exports<'vexflow/src/notesubgroup'>;
}
declare module 'vexflow/src/ornament.js' {
  declare module.exports: $Exports<'vexflow/src/ornament'>;
}
declare module 'vexflow/src/parser.js' {
  declare module.exports: $Exports<'vexflow/src/parser'>;
}
declare module 'vexflow/src/pedalmarking.js' {
  declare module.exports: $Exports<'vexflow/src/pedalmarking'>;
}
declare module 'vexflow/src/raphaelcontext.js' {
  declare module.exports: $Exports<'vexflow/src/raphaelcontext'>;
}
declare module 'vexflow/src/registry.js' {
  declare module.exports: $Exports<'vexflow/src/registry'>;
}
declare module 'vexflow/src/renderer.js' {
  declare module.exports: $Exports<'vexflow/src/renderer'>;
}
declare module 'vexflow/src/stave.js' {
  declare module.exports: $Exports<'vexflow/src/stave'>;
}
declare module 'vexflow/src/stavebarline.js' {
  declare module.exports: $Exports<'vexflow/src/stavebarline'>;
}
declare module 'vexflow/src/staveconnector.js' {
  declare module.exports: $Exports<'vexflow/src/staveconnector'>;
}
declare module 'vexflow/src/stavehairpin.js' {
  declare module.exports: $Exports<'vexflow/src/stavehairpin'>;
}
declare module 'vexflow/src/staveline.js' {
  declare module.exports: $Exports<'vexflow/src/staveline'>;
}
declare module 'vexflow/src/stavemodifier.js' {
  declare module.exports: $Exports<'vexflow/src/stavemodifier'>;
}
declare module 'vexflow/src/stavenote.js' {
  declare module.exports: $Exports<'vexflow/src/stavenote'>;
}
declare module 'vexflow/src/staverepetition.js' {
  declare module.exports: $Exports<'vexflow/src/staverepetition'>;
}
declare module 'vexflow/src/stavesection.js' {
  declare module.exports: $Exports<'vexflow/src/stavesection'>;
}
declare module 'vexflow/src/stavetempo.js' {
  declare module.exports: $Exports<'vexflow/src/stavetempo'>;
}
declare module 'vexflow/src/stavetext.js' {
  declare module.exports: $Exports<'vexflow/src/stavetext'>;
}
declare module 'vexflow/src/stavetie.js' {
  declare module.exports: $Exports<'vexflow/src/stavetie'>;
}
declare module 'vexflow/src/stavevolta.js' {
  declare module.exports: $Exports<'vexflow/src/stavevolta'>;
}
declare module 'vexflow/src/stem.js' {
  declare module.exports: $Exports<'vexflow/src/stem'>;
}
declare module 'vexflow/src/stemmablenote.js' {
  declare module.exports: $Exports<'vexflow/src/stemmablenote'>;
}
declare module 'vexflow/src/stringnumber.js' {
  declare module.exports: $Exports<'vexflow/src/stringnumber'>;
}
declare module 'vexflow/src/strokes.js' {
  declare module.exports: $Exports<'vexflow/src/strokes'>;
}
declare module 'vexflow/src/svgcontext.js' {
  declare module.exports: $Exports<'vexflow/src/svgcontext'>;
}
declare module 'vexflow/src/system.js' {
  declare module.exports: $Exports<'vexflow/src/system'>;
}
declare module 'vexflow/src/tables.js' {
  declare module.exports: $Exports<'vexflow/src/tables'>;
}
declare module 'vexflow/src/tabnote.js' {
  declare module.exports: $Exports<'vexflow/src/tabnote'>;
}
declare module 'vexflow/src/tabslide.js' {
  declare module.exports: $Exports<'vexflow/src/tabslide'>;
}
declare module 'vexflow/src/tabstave.js' {
  declare module.exports: $Exports<'vexflow/src/tabstave'>;
}
declare module 'vexflow/src/tabtie.js' {
  declare module.exports: $Exports<'vexflow/src/tabtie'>;
}
declare module 'vexflow/src/textbracket.js' {
  declare module.exports: $Exports<'vexflow/src/textbracket'>;
}
declare module 'vexflow/src/textdynamics.js' {
  declare module.exports: $Exports<'vexflow/src/textdynamics'>;
}
declare module 'vexflow/src/textnote.js' {
  declare module.exports: $Exports<'vexflow/src/textnote'>;
}
declare module 'vexflow/src/tickable.js' {
  declare module.exports: $Exports<'vexflow/src/tickable'>;
}
declare module 'vexflow/src/tickcontext.js' {
  declare module.exports: $Exports<'vexflow/src/tickcontext'>;
}
declare module 'vexflow/src/timesignature.js' {
  declare module.exports: $Exports<'vexflow/src/timesignature'>;
}
declare module 'vexflow/src/timesignote.js' {
  declare module.exports: $Exports<'vexflow/src/timesignote'>;
}
declare module 'vexflow/src/tremolo.js' {
  declare module.exports: $Exports<'vexflow/src/tremolo'>;
}
declare module 'vexflow/src/tuning.js' {
  declare module.exports: $Exports<'vexflow/src/tuning'>;
}
declare module 'vexflow/src/tuplet.js' {
  declare module.exports: $Exports<'vexflow/src/tuplet'>;
}
declare module 'vexflow/src/vex.js' {
  declare module.exports: $Exports<'vexflow/src/vex'>;
}
declare module 'vexflow/src/vibrato.js' {
  declare module.exports: $Exports<'vexflow/src/vibrato'>;
}
declare module 'vexflow/src/vibratobracket.js' {
  declare module.exports: $Exports<'vexflow/src/vibratobracket'>;
}
declare module 'vexflow/src/voice.js' {
  declare module.exports: $Exports<'vexflow/src/voice'>;
}
declare module 'vexflow/src/voicegroup.js' {
  declare module.exports: $Exports<'vexflow/src/voicegroup'>;
}
declare module 'vexflow/tests/accidental_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/accidental_tests'>;
}
declare module 'vexflow/tests/annotation_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/annotation_tests'>;
}
declare module 'vexflow/tests/articulation_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/articulation_tests'>;
}
declare module 'vexflow/tests/auto_beam_formatting_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/auto_beam_formatting_tests'>;
}
declare module 'vexflow/tests/bach_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/bach_tests'>;
}
declare module 'vexflow/tests/barline_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/barline_tests'>;
}
declare module 'vexflow/tests/beam_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/beam_tests'>;
}
declare module 'vexflow/tests/bend_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/bend_tests'>;
}
declare module 'vexflow/tests/boundingbox_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/boundingbox_tests'>;
}
declare module 'vexflow/tests/clef_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/clef_tests'>;
}
declare module 'vexflow/tests/curve_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/curve_tests'>;
}
declare module 'vexflow/tests/dot_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/dot_tests'>;
}
declare module 'vexflow/tests/easyscore_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/easyscore_tests'>;
}
declare module 'vexflow/tests/factory_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/factory_tests'>;
}
declare module 'vexflow/tests/formatter_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/formatter_tests'>;
}
declare module 'vexflow/tests/ghostnote_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/ghostnote_tests'>;
}
declare module 'vexflow/tests/gracenote_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/gracenote_tests'>;
}
declare module 'vexflow/tests/gracetabnote_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/gracetabnote_tests'>;
}
declare module 'vexflow/tests/key_clef_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/key_clef_tests'>;
}
declare module 'vexflow/tests/keymanager_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/keymanager_tests'>;
}
declare module 'vexflow/tests/keysignature_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/keysignature_tests'>;
}
declare module 'vexflow/tests/mocks.js' {
  declare module.exports: $Exports<'vexflow/tests/mocks'>;
}
declare module 'vexflow/tests/modifier_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/modifier_tests'>;
}
declare module 'vexflow/tests/music_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/music_tests'>;
}
declare module 'vexflow/tests/notehead_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/notehead_tests'>;
}
declare module 'vexflow/tests/notesubgroup_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/notesubgroup_tests'>;
}
declare module 'vexflow/tests/ornament_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/ornament_tests'>;
}
declare module 'vexflow/tests/parser_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/parser_tests'>;
}
declare module 'vexflow/tests/pedalmarking_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/pedalmarking_tests'>;
}
declare module 'vexflow/tests/percussion_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/percussion_tests'>;
}
declare module 'vexflow/tests/registry_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/registry_tests'>;
}
declare module 'vexflow/tests/rests_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/rests_tests'>;
}
declare module 'vexflow/tests/rhythm_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/rhythm_tests'>;
}
declare module 'vexflow/tests/run.js' {
  declare module.exports: $Exports<'vexflow/tests/run'>;
}
declare module 'vexflow/tests/stave_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/stave_tests'>;
}
declare module 'vexflow/tests/staveconnector_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/staveconnector_tests'>;
}
declare module 'vexflow/tests/stavehairpin_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/stavehairpin_tests'>;
}
declare module 'vexflow/tests/staveline_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/staveline_tests'>;
}
declare module 'vexflow/tests/stavemodifier_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/stavemodifier_tests'>;
}
declare module 'vexflow/tests/stavenote_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/stavenote_tests'>;
}
declare module 'vexflow/tests/stavetie_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/stavetie_tests'>;
}
declare module 'vexflow/tests/stringnumber_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/stringnumber_tests'>;
}
declare module 'vexflow/tests/strokes_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/strokes_tests'>;
}
declare module 'vexflow/tests/support/jquery.js' {
  declare module.exports: $Exports<'vexflow/tests/support/jquery'>;
}
declare module 'vexflow/tests/support/qunit.js' {
  declare module.exports: $Exports<'vexflow/tests/support/qunit'>;
}
declare module 'vexflow/tests/support/raphael.js' {
  declare module.exports: $Exports<'vexflow/tests/support/raphael'>;
}
declare module 'vexflow/tests/tabnote_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/tabnote_tests'>;
}
declare module 'vexflow/tests/tabslide_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/tabslide_tests'>;
}
declare module 'vexflow/tests/tabstave_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/tabstave_tests'>;
}
declare module 'vexflow/tests/tabtie_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/tabtie_tests'>;
}
declare module 'vexflow/tests/textbracket_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/textbracket_tests'>;
}
declare module 'vexflow/tests/textnote_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/textnote_tests'>;
}
declare module 'vexflow/tests/threevoice_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/threevoice_tests'>;
}
declare module 'vexflow/tests/tickcontext_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/tickcontext_tests'>;
}
declare module 'vexflow/tests/timesignature_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/timesignature_tests'>;
}
declare module 'vexflow/tests/tuning_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/tuning_tests'>;
}
declare module 'vexflow/tests/tuplet_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/tuplet_tests'>;
}
declare module 'vexflow/tests/vexflow_test_helpers.js' {
  declare module.exports: $Exports<'vexflow/tests/vexflow_test_helpers'>;
}
declare module 'vexflow/tests/vibrato_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/vibrato_tests'>;
}
declare module 'vexflow/tests/vibratobracket_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/vibratobracket_tests'>;
}
declare module 'vexflow/tests/voice_tests.js' {
  declare module.exports: $Exports<'vexflow/tests/voice_tests'>;
}
declare module 'vexflow/tools/generate_svg_images.js' {
  declare module.exports: $Exports<'vexflow/tools/generate_svg_images'>;
}
